"""init

Revision ID: 51ca7bbe4745
Revises: 
Create Date: 2026-02-19 00:21:53.655600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ca7bbe4745'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sonarr_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sonarr_id', name='uq_series_sonarr_id')
    )
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cross_seed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cross_seed_id'], ['torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash', name='uq_torrents_hash')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('latest_torrent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['latest_torrent_id'], ['torrents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie_id', 'season', 'episode', name='uq_episode_series_season_episode')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index('ix_episode_series_season_episode', ['serie_id', 'season', 'episode'], unique=False)

    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radarr_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('latest_torrent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['latest_torrent_id'], ['torrents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('radarr_id', name='uq_movies_radarr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index('ix_episode_series_season_episode')

    op.drop_table('episodes')
    op.drop_table('torrents')
    op.drop_table('series')
    # ### end Alembic commands ###
