"""Add Celery-ID in Deferred Table

Revision ID: 7be36deabe39
Revises: dfe88bd564ee
Create Date: 2026-03-01 14:56:38.671105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be36deabe39'
down_revision = 'dfe88bd564ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deferred_deletions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deferred_deletions', schema=None) as batch_op:
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###
