"""empty message

Revision ID: dfe88bd564ee
Revises: 2cfd16f9c792
Create Date: 2026-02-25 20:25:13.076175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe88bd564ee'
down_revision = '2cfd16f9c792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deferred_deletions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('torrent_hash', sa.String(length=128), nullable=False),
    sa.Column('can_be_deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_hash', name='uq_deferred_torrent_hash')
    )
    with op.batch_alter_table('deferred_deletions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deferred_deletions_torrent_hash'), ['torrent_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deferred_deletions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deferred_deletions_torrent_hash'))

    op.drop_table('deferred_deletions')
    # ### end Alembic commands ###
